### ISSUE TITLE
Lua, rlua, and threads

### ISSUE THREAD

**Issue by czak** [kyren/rlua#109]
Please forgive any possible silliness in this post. I'm still new to Rust and perhaps looking in all the wrong directions.

I'm evaluating `rlua` for the following use case:

1. I want Lua running (in) the main loop of my program
2. I also want a Lua REPL accessible (via stdin or a socket - irrelevant for this discussion) sharing global Lua state with (1).

I figured I need threads and I got a basic sample of this working in C [in this gist](https://gist.github.com/czak/487220502aaba31102130ef2598f953c).

I'm trying to figure out how to do the same in Rust with `rlua`. I'm currently stuck at `borrow of moved value` after I `thread::spawn` my REPL thread. I'm now looking into `Arc` et al, but that's not yielding more success at the moment. Is there a thread-based solution to this with `rlua`? Should I be looking for something entirely different?

### Note about the C version

I keep reading that Lua is not thread-safe. However, I've done some basic tests (e.g. increment a global counter from multiple threads at a time) and had good results with:

* `lua_newthread`
* `lua_lock` and `lua_unlock` implemented with `pthread_mutex_lock` and `pthread_mutex_unlock`

Am I misunderstanding the way Lua should be used with threads?

**Comment by Shiroy** [comment]
[According to the documentation](https://docs.rs/rlua/0.15.3/rlua/struct.Lua.html#implementations) `rlua::Lua` is [`Send`](https://doc.rust-lang.org/std/marker/trait.Send.html) but not [`Sync`](https://doc.rust-lang.org/std/marker/trait.Sync.html).

This means that you can transfer the Lua structure between threads but it is forbidden to have references to the same object shared across threads. That would opens the door to unsynchronized mutations that is the root of all the evil in multi-threading programming.

To share your Lua structure between threads, you have to wrap it within a [`Mutex`](https://doc.rust-lang.org/std/sync/struct.Mutex.html). A mutex takes everything that is `Send` and makes it `Send + Sync` by controlling which thread can access the resource at a particular time, at runtime (you have to lock the mutex before accessing the shared resource).

### Thoughts about your error

I presume that in your code, you wrote something like:
```rust
let lua = Lua::new();

thread::spawn(move || {
    lua.do_something();
});

lua.do_something_else();
```

When you reach `thread::spawn`, because of the `move` keyword, `lua`'s ownership is transferred to the new thread, which is fine because `rlua::Lua` implements `Send`. Therefore, you can't access the `lua` variable below `spawn` because it doesn't belong to the main thread any more.

If you remove the `move` keyword, only a reference to `lua` will be transferred to the new thread. To make a reference shareable between threads, the structure must implement `Sync`. `rlua::Lua` explicitly disallow this by disabling the automatic `Sync` implementation (wrongly inferred by the compiler because of the unsafety of C [*I'm not sure about this*]).

More information on how Rust manages concurrency : https://doc.rust-lang.org/book/ch16-00-concurrency.html

**Comment by czak** [comment]
Thank you for a great explanation @Shiroy. I had some more time to test and got a minimal sample working with `Arc` & `Mutex`. If anyone's interested:

```rust
use std::io;
use std::time;
use std::sync::{Arc, Mutex};
use std::thread::{self, JoinHandle};
use rlua::Lua;

// fake repl
// type in "done = true" to quit the main loop
fn start_repl(luarc: Arc<Mutex<Lua>>) -> JoinHandle<()> {
    thread::spawn(move || {
        let mut input = String::new();
        io::stdin().read_line(&mut input).unwrap();

        let lua = luarc.lock().unwrap();
        lua.context(|lua| {
            lua.exec::<_, ()>(&input, None).unwrap();
        });
    })
}

fn main() {
    let luarc = Arc::new(Mutex::new(Lua::new()));
    let repl = start_repl(luarc.clone());

    loop {
        println!("In main loop...");
        thread::sleep(time::Duration::from_secs(1));

        let lua = luarc.lock().unwrap();
        if lua.context(|lua| lua.eval::<_, bool>("done", None).unwrap()) {
            break;
        }
    }

    repl.join().unwrap();
}
```

There are 2 threads sharing `luarc: Arc<Mutex<Lua>>`. When either one needs to do some Lua, it calls `luarc.lock()`.

I think it can work, although one needs to be very careful with locking so that other threads get their chance.
