### ISSUE TITLE
[Request] impl FromLua for &T and &mut T if T implements UserData

### ISSUE THREAD

**Issue by rsKliPPy** [kyren/rlua#114]
Right now there's only
```rust
impl<'lua, T: 'static + UserData + Clone> FromLua<'lua> for T { }
```
but I'd like these to exist as well
```rust
impl<'lua, T: 'static + UserData> FromLua<'lua> for &T { }
impl<'lua, T: 'static + UserData> FromLua<'lua> for &mut T { }
```
and their `from_lua` methods would return `Result<&'lua T>` and `Result<&'lua mut T>`, respectively. This would avoid copying when possible and would allow you to mutate a userdatum from any function, not just its methods (if this is even desirable?).

I haven't tested this impl though and I don't know if there are any gotchas or if there will be troubles with the lifetimes of these references. Maybe there's already a way to do this that I'm missing?

**Comment by kyren** [comment]
You can't *in general* give Lua anything non-'static, because inside Lua everything can live for an arbitrary amount of time.  This is the reason that, *in general* functions and UserData are required to be 'static.

Fortunately, there's a whole system in `rlua` to safely get around this limitation: [Scope](https://docs.rs/rlua/0.16.1/rlua/struct.Scope.html)

You still can't directly pass a &T or &mut T where T: UserData, but you can create a UserData that contains one, or implement UserData directly for &T / &mut T even.

**Comment by rsKliPPy** [comment]
I think there's a misunderstanding. Here's some example code:
```rust
use rlua::{self, Lua, AnyUserData, UserData, UserDataMethods, MetaMethod};

fn main() -> rlua::Result<()> {
    let lua = Lua::new();

    #[derive(Debug)]
    struct Point2D {
        pub x: i32,
        pub y: i32,
    }

    impl UserData for Point2D {
        fn add_methods<'lua, T: UserDataMethods<'lua, Self>>(methods: &mut T) {
            methods.add_meta_method(MetaMethod::ToString, |_, this, ()| {
                Ok(format!("{:?}", this))
            });
        }
    }

    impl Clone for Point2D {
        fn clone(&self) -> Self {
            println!("Cloned");
            Point2D { x: self.x, y: self.y }
        }
    }

    lua.context(|ctx| {
        let globals = ctx.globals();
        globals.set("point", Point2D { x: 10, y: 20 })?;

        let func1 = ctx.create_function(|_, mut point: Point2D| {
            println!("func1");
            point.x = 30;
            Ok(())
        })?;

        let func2 = ctx.create_function(|_, ud: AnyUserData| {
            println!("func2");
            if let Ok(mut point) = ud.borrow_mut::<Point2D>() {
                (*point).x = 40;
            }
            Ok(())
        })?;

        globals.set("func1", func1)?;
        globals.set("func2", func2)?;

        ctx
            .load("func1(point); print(point); func2(point); print(point);")
            .exec()?;
        
        Ok(())
    })?;

    Ok(())
}

```
Output:
```
Cloned
Point2D { x: 10, y: 20 }
Point2D { x: 40, y: 20 }
```
`func2` gets a mutable reference to the original `Point2D` object, but it's not really ergonomic. It's impossible to just have `ud: &Point2D` as a function parameter.

However with this patch:
```diff
diff --git a/src/conversion.rs b/src/conversion.rs
index b4c031e..5317ebc 100644
--- a/src/conversion.rs
+++ b/src/conversion.rs
@@ -1,3 +1,4 @@
+use std::cell::RefMut;
 use std::collections::{BTreeMap, HashMap};
 use std::ffi::{CStr, CString};
 use std::hash::{BuildHasher, Hash};
@@ -140,6 +141,19 @@ impl<'lua, T: 'static + UserData + Clone> FromLua<'lua> for T {
     }
 }
 
+impl<'lua, T: 'static + UserData> FromLua<'lua> for RefMut<'lua, T> {
+    fn from_lua(value: Value<'lua>, _: Context<'lua>) -> Result<RefMut<'lua, T>> {
+        match value {
+            Value::UserData(ud) => Ok(ud.borrow_mut::<T>()?),
+            _ => Err(Error::FromLuaConversionError {
+                from: value.type_name(),
+                to: "userdata",
+                message: None,
+            }),
+        }
+    }
+}
+
 impl<'lua> ToLua<'lua> for Error {
     fn to_lua(self, _: Context<'lua>) -> Result<Value<'lua>> {
         Ok(Value::Error(self))
diff --git a/src/userdata.rs b/src/userdata.rs
index b43a609..805d513 100644
--- a/src/userdata.rs
+++ b/src/userdata.rs
@@ -319,7 +319,7 @@ impl<'lua> AnyUserData<'lua> {
     ///
     /// Returns a `UserDataBorrowMutError` if the userdata is already borrowed. Returns a
     /// `UserDataTypeMismatch` if the userdata is not of type `T`.
-    pub fn borrow_mut<T: 'static + UserData>(&self) -> Result<RefMut<T>> {
+    pub fn borrow_mut<T: 'static + UserData>(&self) -> Result<RefMut<'lua, T>> {
         self.inspect(|cell| {
             Ok(cell
                 .try_borrow_mut()
@@ -363,7 +363,7 @@ impl<'lua> AnyUserData<'lua> {
     fn inspect<'a, T, R, F>(&'a self, func: F) -> Result<R>
     where
         T: 'static + UserData,
-        F: FnOnce(&'a RefCell<T>) -> Result<R>,
+        F: FnOnce(&'lua RefCell<T>) -> Result<R>,
     {
         unsafe {
             let lua = self.0.lua;
```
it's possible to have `mut ud: RefMut<Point2D>` at least, and we can do it for `Ref<T>` as well. I wasn't able to get it to work with `&mut T` because of conflicting implementations.

**Comment by kyren** [comment]
The first thing that sticks out at me is that this is unsound, this line:

```
+    pub fn borrow_mut<T: 'static + UserData>(&self) -> Result<RefMut<'lua, T>> {
```

Is not sound, because it is very important that the `RefMut` have the lifetime of the *handle*.  Without this, it would be possible for Lua to set the variable to Nil, then garbage collect, thus invalidating the `RefCell` behind it.  Trying to figure out if there's a way around this...

**Comment by kyren** [comment]
> Oh, my bad, I haven't even realized that. 😕

No problem, you were actually perfectly clear except for just that, I just somehow managed to miss ALL of the other information 😛

**Comment by kyren** [comment]
No, I don't think that there's any way to provide a safe `FromLua` for Ref / RefMut due to garbage collection unfortunately.  There could be some kind of specific interface *just* for callback parameters, since it would be possible to ensure that they lived for the lifetime of the callback, but it would be much more involved and would be a special case for callback parameters.  I wonder if that's worth it...

**Comment by rsKliPPy** [comment]
It's definitely not worth it only for parameters, because this would prove useful to other things like referencing userdata fields within tables.
So for how long can you keep the reference around when you call `AnyUserData::borrow[_mut]`? I really don't know the inner workings of rlua so I'm not sure what's considered safe.

**Comment by kyren** [comment]
> So for how long can you keep the reference around when you call AnyUserData::borrow[_mut]? I really don't know the inner workings of rlua so I'm not sure what's considered safe. Is my func2 in the example code safe?

If you're using `rlua` without the `unsafe` keyword, it should be 100% safe, so your example is safe.

The following is not so much for you (I get the impression you know this already), but for anybody reading along...

If your module has a safe interface, it means that anything that you can possibly do without typing `unsafe` *better be safe*.  That's what it means to be "sound", a safe (really!) interface to unsafe code.  `rlua` is, at the time of this writing, as *far as I know*, sound.  To make a slightly finer point, the *goal* is for it to be sound, so this is not counting any bugs that may exist in `rlua` that make it unsound, but these are considered the most serious kind of bug, and if you find one I will basically *stop everything I'm doing to go fix it*.

Your example is safe because it has to be, if you could demonstrate UB while using `rlua`, that would *by definition* be a bug in `rlua`.  This is precisely the beauty and utility of rust's safe / unsafe divide!

With that out of the way, the patch that you wrote is *not* sound, because it introduces potential UB to `rlua`'s safe interface.  How can this be, since your patch does not use the `unsafe` keyword?  Well, `unsafe` kind of [pollutes a whole module](https://doc.rust-lang.org/nomicon/working-with-unsafe.html).  It's important to understand the distinction here, a safe interface is a *contract*, if you can cause UB with a safe interface, the bug lies in the person that implemented the interface.  If you write unsafe code yourself, it may depend on the behavior of code that is not marked with unsafe that you also control that also implements the same safe contract, as is the case here.

Sorry to use this issue to harp on the distinction, but I get the impression that there is rust code out there that causes UB through a safe interface and somehow people are okay with this.

**Comment by kyren** [comment]
> I guess

```
let point = ud.borrow_mut::<Point2D>()?;
```

> is not that bad to be honest, if it's safe that is.

It is safe as far as I can tell, if you can disprove it *tell me* and I'll fix it.  I take things like this very seriously, this kind of thing is kind of rust's *raison d'etre*.

**Comment by rsKliPPy** [comment]
Yeah I get now why it is unsound, didn't think about that when I made the patch. Thanks!
I guess this can be closed now.

**Comment by kyren** [comment]
> Yeah I get now why it is unsound, didn't think about that when I made the patch. Thanks!
I guess this can be closed now.

Sorry, and I know that it's kind of unergonomic, lots of things in `rlua` are.  Eventually (probably in the context of `luster`) I'm going to do more work to try and improve it in other ways.
