### ISSUE TITLE
Chunk Caching

### ISSUE THREAD

**Issue by ducharmemp** [kyren/rlua#115]
Hi there! I'm relatively new to rust and lua, so forgive me if this isn't something possible or if it's more or less frowned upon. I'm writing a game and using rlua to attach scripts to entities, but I'd rather avoid having to re-parse the buffer every frame. It's a bit of a premature optimization on my part, but is there any idiomatic way to keep around the chunks returned from the Lua object? I had some trouble since they really depend on the context and its lifetime parameters.

I was thinking that a nice thing would be to have some lru cache that would return an integer handle to uniquely identify the chunk, so that you could reach into the Lua object and re-execute that same script using only the handle, but if the script fell out of the cache you'd have to re-compile. Thoughts?

**Comment by kyren** [comment]
A `Chunk` in rlua is probably not what you're thinking it is.  I'm not totally happy with the naming here, but a `Chunk` is just a builder pattern to load Lua scripts, it doesn't actually represent a compiled Lua chunk.  The reason for this is that how Lua represents compiled Chunks actually leaves a bit to be desired: it is not possible to set the 'name' after a chunk is loaded, and it is not desirable to change the `_ENV` upvalue more than once per chunk*  so, the `Chunk` in rlua doesn't actually do anything, it just sets up for a later call to `luaL_loadbuffer`.  If you could somehow cache rlua `Chunk`s, it would be no better than recompiling.

(*) So why is it not desirable to set the `_ENV` upvalue of a chunk to a different value more than once?  What I imagine you want to do is have a script that contains, say, several functions, and you compile it once, but "instantiate" it in several independent instances.  I've had to do this specific thing before, and you will probably hate the answer: the only way I know of with PUC-Rio Lua or its derivatives to *perfectly independently* cache compiled chunks is to: 1) output them to bytecode, cache *that*, then reload the bytecode into a new chunk function ☹️

If that sounds terrible, it kind of is.  The reason for this is, when Lua compiles a chunk, it returns a function.  This function has a single upvalue for `_ENV` inside the chunk, which is generally the globals table (`_G`), but can also be any other table.  Generally, this chunk is executed in order to place things into its environment (like a set of other functions), or sometimes people will return tables from the chunk that also contain functions, but in all but the simplest cases, executing the chunk makes internal chunk *functions* available somehow, and this is where things go wrong.

The problem is, that the first upvalue for the chunk (`_ENV`) is also shared by all of the inner chunk functions, so *their* `_ENV` points to the outer chunk upvalue by *reference*.  How this works internal to the Lua VM is somewhat complicated, but the end result is that if you change the `_ENV` upvalue of the chunk function and re-run it, *you will also change the `_ENV` upvalue of the original inner functions*.

So, you cannot re-use a chunk function without it sharing the environment, which is probably not what you want (or you would just use some other easier mechanism for sharing).  This is why `rlua` only allows you to specify the environment for a loaded chunk once at load time, because otherwise it would not do what you want, or even anything remotely reasonable.  This reflects the same API provided to lua scripts: `load` takes an optional chunkname and env parameter, and that's all you get.

The only way I ever figured that even *might* be possible to fix this would be to somehow walk the resulting environment in its entirety, then if a value is a function, check its upvalues against the previous `_ENV` table and replace it, then also walk all of the other upvalues recursively, etc.  This.. *might* be possible using the Lua C API, I don't know.  The simpler and terrible way to do this is simply keep the bytecode around and reload it 🤷‍♀️

If you wanted to cache bytecode, *technically* I believe that `Context::load` will also accept bytecode, but not for very long, as I'm currently removing this ability.  Since bytecode can cause memory unsafety in the compiler, that ability is actually a soundness bug, so even if I eventually add it back, it will have to be behind an unsafe flag.

What might be easier is just re-structuring things so that there do not have to be many independent lua contexts, or simply just by policy enforce that script functions should not share state between calls.  I'm sorry there's not a better answer here 😢

**Comment by ducharmemp** [comment]
Wow! Thanks for the detailed answer. Honestly, all of the reasons that you outlined above as to why I *wouldn't* want to cache the chunk make total sense, and although I'm sure caching the bytecode might lead to some speedups, I'm positive that the overall gains probably aren't worth it right now. I might play around with the edit idea just to see how that fits with my ECS implementation, but again I bet it's really just a premature optimization on my end. It's not like I'm going to be making the next DICE or Blizzard game after all 😄 

Thanks for such a detailed answer, I'll go ahead and close the issue!
