### ISSUE TITLE
Older Lua versions?

### ISSUE THREAD

**Issue by dbeckwith** [kyren/rlua#125]
Any possibility of using this library with Lua 5.2? Maybe as a feature? I think the only rlua API difference would be removing `Value::Integer`. I'd be open to submitting a PR.

**Comment by kyren** [comment]
Sorry for the delayed response, mostly what is blocking this is that I get the impression that cargo features are NOT the way to do this.  I suspect if multiple separate Lua versions are selected in this way that it would cause problems, but I don't know what the correct solution is.  It might be that the proper way to do this is to have multiple different crates with the same source code, somehow built programmatically?  If you can come up with a good answer here (and by side effect, a good answer for built-in vs system Lua versions), I would be more open to solving this.

**Comment by dbeckwith** [comment]
If your only concern with cargo features is that a user could select multiple of them, I think just enforcing at compile time that the different features (for each version and built-in vs. system) are exclusive is not difficult. Using something like [`cfg-if`](https://crates.io/crates/cfg-if) might make it easier. The pattern of using features is used by [`gtk`](https://github.com/gtk-rs/gtk/blob/master/Cargo.toml#L25). If most of the glue code ends up being the same between two versions like 5.3 and 5.2 which are mostly similar, then using features to conditionally compile just the differences between them makes sense to me.

I should also mention that I attempted to implement this myself using features to select which version was built, and the approach seemed sound, but I just got bogged down in trying to get the actual bindgen to work right.

**Comment by khvzak** [comment]
[mlua](https://github.com/khvzak/mlua) has support of Lua 5.1/5.2/5.3 (including LuaJIT) and has forked from rlua 0.15

**Comment by dbeckwith** [comment]
Great, I'll check it out, thanks!

**Comment by kyren** [comment]
I do not have a lot of time lately to do the proper amount of work for rlua, mostly because I just personally no longer use Lua at all so it's hard for me to justify spending time on this.

It would be really great if all the people who use Lua in Rust or want to add features to rlua as a fork could somehow work together on a *sound* crate to do it.  I haven't looked at mlua in depth but it is definitely not sound.  It might be great, but it would be a huge shame if all the effort I spent trying to make a sound Lua API went to waste.
