### ISSUE TITLE
How to access a local rlua::Value in create_function?

### ISSUE THREAD

**Issue by slmjkdbtl** [kyren/rlua#130]
```rust
let mut t = ctx.create_table()?;
ctx.scope(|scope| {
	scope.create_function(|_, ()| {
		return Ok(t);
	});
});
```
why isn't `t` accessible in `scope.create_function`?

My real case though, is I'm trying to write a function to add a `rlua::Value` to `package.preload` so I can load the thing with `require` in lua
```rust
fn add_mod(ctx: &Context, name: &str, val: Value) -> rlua::Result<()> {
	let preloads: Table = ctx.globals().get::<_, Table>("package")?.get("preload")?;
	ctx.scope(|scope| {
		preloads.set(name, scope.create_function(|ctx, ()| {
			return Ok(val);
		}));
	});
	return Ok(());
}
```
however, it says
```
`*mut rlua::ffi::lua_State` cannot be shared between threads safely
`*mut std::marker::PhantomData<std::cell::UnsafeCell<()>>` cannot be shared between threads safely
```
need some help on how to get this to work. Thanks

**Comment by kyren** [comment]
You don't want to use scope, what you probably want is to use something like [Function::bind](https://docs.rs/rlua/0.16.3/rlua/struct.Function.html#method.bind) to associate a Lua value with a callback function.

Alternately, you can use registry values to make whatever Lua values you want available to anything that has access to the Lua state.

You don't want to put the "smart handle" types into userdata or callbacks -- it usually isn't allowed at all due to lifetimes, but it will sort of half work when using a scope, but you just shouldn't do it.  The Lua C API does not give the direct ability for users to interact with the garbage collector, so any rust type like this that holds a Lua handle can't participate in garbage collection, and it is very easy to make unbreakable cycles.  Lua does give us some tools to tie Lua values to callbacks / userdata in ways that they DO participate in garbage collection though, which are exposed in rlua as e.g. Function::bind and AnyUserData::set_user_value.

If you use registry values you won't run into any lifetime issues, but all the garbage collector problems still exist, so you should only do they when the number and type of registry values is pretty limited.  If you need a limited constant number of such values, the registry can be useful (you don't run into these sorts of problems with names registry values generally).

**Comment by slmjkdbtl** [comment]
@kyren Thank you so much for the explanation! I'm now able to accomplish my goal with `Function::bind` + registry like this:
```rust
let preloads: Table = ctx.globals().get::<_, Table>("package")?.get("preload")?;
let f = ctx.create_function(|_, (v): (Value)| {
	return Ok(v);
})?;
let key = ctx.create_registry_value(json)?;
preloads.set(name, f.bind(ctx.registry_value::<Value>(&key)?)?)?;
```
however I still have got those `* cannot be shared between threads safely` error if I try to pack them into a function
```rust
impl<'lua> ContextExt for Context<'lua> {
	fn add_module<T: ToLua<'lua>>(&self, name: &str, val: T) -> rlua::Result<()> {
		let preloads: Table = self.globals().get::<_, Table>("package")?.get("preload")?;
		let f = self.create_function(|_, (v): (Value)| {
			return Ok(v);
		})?;
		let key = self.create_registry_value(val)?; // error here
		preloads.set(name, f.bind(self.registry_value::<Value>(&key)?)?)?;
		return Ok(());
	}
}
let test = ctx.create_table();
ctx.add_module("test", test); 
// `*mut rlua::ffi::lua_State` cannot be sent between threads safely
// `*mut std::marker::PhantomData<std::cell::UnsafeCell<()>>` cannot be sent between threads safely
```
still not sure what I'm doing wrong here (I'm still not good at lifetimes sorry if I'm asking newbie questions here)

**Comment by kyren** [comment]
I think you're just missing a Send bound on T.

**Comment by slmjkdbtl** [comment]
It still produces the same errors if I add a `Send` bound to T.

Here's a playground showing the minimal code and the error:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=360089935a5d5f8c52a2d94f0f3cab51

Again thanks for the time for looking at my problem, I really can't get around with it by myself.

**Comment by kyren** [comment]
Ugh, sorry no I was wrong you shouldn't have a Send bound, I'm still half asleep 😛

The example you gave me has several problems that would prevent it from compiling, but what you originally wanted to do seems to work fine?

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d5204ef71770caa243f331d239750eb8

**Comment by slmjkdbtl** [comment]
Thank you! That works. 

What about the second question in the playground above? Is there a way I can pass a mutable userdata reference to a `rlua::Function::call`?

**Comment by kyren** [comment]
Yes, indirectly.

Generally, there's no way to pass non-'static data to Lua safely.  How could you, Lua has no concept of lifetimes and things can be stored anywhere in the global Lua environment and live for a completely arbitrary amount of time, so anything with pointers is not going to be safe to give to Lua without extra work such as marking the pointer when it's known to be invalidated and protecting it from access somehow.

But, you don't have to do this yourself, because rlua already does this for you via `Context::scope`!  Methods in the returned `Scope` do NOT require that the data passed in be 'static, however *once the scope ends, the values are invalidated*.  This means that outside the `Context::scope` call, if Lua tries to use one of these values it will trigger some kind of Lua error with a message like "callback has been invalidated".

So, if you want to give some Lua code a `&mut` reference (or any kind of non-'static reference), you can do it either via non-'static callbacks or non-'static userdata, both of which are only possible via `Context::scope`.

**Comment by slmjkdbtl** [comment]
I understand that with scope I can modify values that are not static, like the example in `guided_tour.rs`, but I looked at the four methods provided by `Scope` and still couldn't figure out how to use scope to pass a mutable shared data to a lua function callback. 

Consider this example for a windowed application api (sorry for being verbose, I made the code as minimal as I can):
```rust
use rlua::*;

struct Window;

#[derive(Default, Clone)]
struct State {
	n: i32,
}

impl State {
	fn add(&mut self) {
		self.n += 1;
	}
}

impl Window {
        // workaround, state created by user and passed to window
	fn run(&mut self, mut state: &mut State, mut f: impl FnMut()) {
		loop {
			f();
		}
	}
        // desired, state created and managed by Window
	fn run_owned(&mut self, mut f: impl FnMut(&mut State)) {
		let mut state = State::default();
		loop {
			f(&mut state);
		}
	}
}

fn main() -> rlua::Result<()> {

	let lua = Lua::new();

	return lua.context(|ctx| {

		let globals = ctx.globals();

		impl UserData for State {

			fn add_methods<'lua, M: rlua::UserDataMethods<'lua, Self>>(methods: &mut M) {
				methods.add_method_mut("add", |_, state: &mut State, ()| {
					return Ok(state.add());
				});
				methods.add_method("get", |_, state: &State, ()| {
					return Ok(state.n);
				});
			}

		}

		impl UserData for &mut State {}

		impl UserData for Window {

			fn add_methods<'lua, M: UserDataMethods<'lua, Self>>(methods: &mut M) {

				// workaround
				methods.add_method_mut("run", |ctx, win: &mut Window, (mut state, cb): (State, rlua::Function)| {
					return Ok(win.run(&mut state, || {
						cb.call::<_, ()>(());
					}));
				});

				// desired
				methods.add_method_mut("run_owned", |ctx, win: &mut Window, (cb): (rlua::Function)| {
					return Ok(win.run_owned(|state: &mut State| {
						// lifetime error here, this line won't compile
						cb.call::<_, ()>(state);
					}));
				});

			}

		}

		globals.set("create_window", ctx.create_function(|_, ()| {
			return Ok(Window);
		})?)?;

		globals.set("create_state", ctx.create_function(|_, ()| {
			return Ok(State::default());
		})?)?;

		// desired, don't know how to get it work
		ctx.load(r#"
			local win = create_window()
			win:run_owned(function(state)
				state:add()
				print(state:get())
			end)
		"#).exec().expect("oh no");

		// workaround, works fine
		ctx.load(r#"
			local win = create_window()
			local state = create_state()
			win:run(state, function()
				state:add()
				print(state:get())
			end)
		"#).exec().expect("oh no");

		return Ok(());

	});

}
```
this example contains a workaround which let user control the `State` instead of being created and managed by `Window`, (which I'm actually not sure if this is a better api. `State` is for storing data like input, graphics states, modified by the event loop in `Window`, and provide users with methods like `state:key_is_pressed(...)`)

**Comment by slmjkdbtl** [comment]
Actually, I think letting user create the window context is better now, so I might stick with my workaround, but I'm still curious of how to achieve what I was originally trying to do.

**Comment by kyren** [comment]
Okay, so `State` implements `UserData` and since any `T: UserData + Clone` will implement `FromLua` automatically, you can accept it as a callback parameter *but rlua will implicitly clone it* as you've discovered.  It's arguable that we should remove the automatic `FromLua` impl for `T: UserData + Clone`, because it's a bit surprising...

What you can do instead though, is accept an `AnyUserData` handle instead of a bare `State`.  An `AnyUserData` is a handle to the *Lua-owned* instance of a `UserData`, and it is sharable and internally mutable like any Lua normal Lua value.  However, also just like any other Lua value, you have to rely on dynamic typing, so you have to try to get a specific type out of an `AnyUserData` handle and fail in some way if the type is incorrect.  This will prevent rlua from implicitly cloning your value.

You can also remove the `Clone` impl for `State` if it's not something that should be cloned, because `Clone` is not a requirement for `UserData`, only for the automatic `FromLua` impl for userdata.

**Comment by slmjkdbtl** [comment]
I see. I'm able to use `AnyUserData` and successfully pass and cast a mutable reference _from lua to rust_, but I just found that my code above
```lua
state = create_state()
win:run(state, function()        -- mutable borrow here
        state:add()              -- mutable borrow again
end)
```
violates the ownership rules so it'll never work. So I have to go my original route, which is to pass the mutable ref from lua to rust (pass that `&mut State` to `rlua::Function`), which is 

```rust
impl Window {
	fn run(&mut self, mut f: impl FnMut(&mut State)) {
		let mut state = State { n: 0 };
		loop {
			f(&mut state);
		}
	}
}
methods.add_method_mut("run", |ctx, win: &mut Window, (cb): (rlua::Function)| {
	return Ok(win.run(|state: &mut State| {
		// lifetime error here
		cb.call::<_, ()>(state);
	}));
});
```
lua side:
```lua
local win = create_window()
win:run(function(state)
	state:add()
end)
```
feel like I've been asking the same question over and over.. appreciate the patience. I'm able do certain things with `Scope` and `AnyUserData`, but I still cannot solve my particular problem

**Comment by kyren** [comment]
The fact that you're implementing UserData for  &mut T directly is pretty weird, I guess there's nothing wrong with it, but it makes it a bit difficult to realize what's going on.

It looks like where you call the callback, you're passing in a bare &mut T.  Let's break down what I think is happening.

&mut T implements UserData, so &mut T therefore implements ToLua automatically.  However, when you try to use it, you get a lifetime error since your particular &mut T isn't 'static (I mean, no &mut T should ever be 'static, but that's besides the point) and the automatic impl only works for static T: UserData.

So, exactly what you have there should work IF you put the cb.call in a scope, and manually turn the &mut State into a UserData with create_nonstatic_userdata (rather than relying on the automatic version which is not scoped).

Now, there might be a simpler design for what you're trying to do, but it's hard for me to know for sure.

**Comment by slmjkdbtl** [comment]
I've tried `create_nonstatic_userdata` before but now I finally got it working! The problem was I can't access `state`'s methods in lua if I do it this way. It turns out I have to define all the methods in `impl Userdata for &mut State` instead of `impl UserData for State` since the value I'm passing to `create_nonstatic_userdata` is a `&mut State`.

Thanks for the help!
