### ISSUE TITLE
Why does the closure argument in `create_function` need to be `Send`?

### ISSUE THREAD

**Issue by crides** [kyren/rlua#160]
Hi, I'm trying to use `rlua` to provide scripting access to some Rust resources which include a database connection. I'm borrowing the connection inside a closure passed as argument to `create_function`. The connection is `!Send`, but the closure argument is required to be `Send`. After looking through some code, I still don't understand why the requirement exist. It doesn't seem like `create_callback` and the underlying ffi interface requires the closure to be `Send`, and since `rlua::Lua` is also not `Send`, the closure shouldn't be required to be `Send` either. Is there something I'm missing here?

Talking about the actual problem, I worked around it now by using [`rust-fragile`](https://github.com/mitsuhiko/rust-fragile), as I know there will be no multithreaded access. But I don't know if that's the best way to deal with it.

**Comment by kyren** [comment]
Unfortunately I didn't come up with a good way of abstracting between Send and !Send when I initially made rlua, so I made the decision to require everything stored inside the runtime to be Send so that the Lua state itself could safely be Send.  I needed it for game systems that were individually single threaded but would be run on a thread pool, so the top-level Lua state being Send (but not sync) was a requirement.

Ideally, you would be able to choose between two completely separate Send and !Send APIs, but designing that is a bit of work, and nobody (including me) has taken up that challenge yet.

**Comment by kyren** [comment]
Yeah the top level Lua is send, whew I was worried there for a moment, you can see in the docs here: https://docs.rs/rlua/0.17.0/rlua/struct.Lua.html

**Comment by kyren** [comment]
> Talking about the actual problem, I worked around it now by using rust-fragile, as I know there will be no multithreaded access. But I don't know if that's the best way to deal with it.

rust-fragile seems like a good solution that doesn't require unsafe.  The ideal solution would be having two parallel APIs provided by rlua somehow.

**Comment by kyren** [comment]
Oh, one more possibility is to use a single giant Scope to create !Send userdata and callbacks.  You'd have to structure the code so that the Scope was alive for the entire life of the API, which might be even more annoying than rust-fragile, but just throwing it out there as a possibility in case it's more acceptable.

**Comment by crides** [comment]
Thanks for the very detailed response! Sorry I got a little confused from the older issues about whether `rlua::Lua` is `Send` or not. For now, either `rust-fragile` or `Context::scope` works, although I'll probably be changing the structure of my program later on as it is simply a test right now. Thanks very much for the help!
