### ISSUE TITLE
Guided Tour implies no GC running when using Scope

### ISSUE THREAD

**Issue by oberien** [kyren/rlua#74]
In the Guided Tour example, [the comment above the `.scope` code](https://github.com/chucklefish/rlua/blob/master/examples/guided_tour.rs#L147-L151) could imply that no GC is running while using the scope. At least that's how I understood it at first.
After a small test I'm pretty certain that the GC is running when inside a scope, so I guess this is just an unfortunately phrased comment.

**Comment by kyren** [comment]
Yeah the GC is running in a call to `Lua::scope` for sure, the text "lifting both of these restrictions" is meant to reference the fact that userdata must be `Send` and `'static`.  I'll figure out a better way of wording it, or simply drop the reference to the GC at all.

The reason I mention the GC is because that is the reason WHY userdata must be `'static`; since we don't know when Lua will get around to dropping our type, we can't make any assumptions about the lifetimes of any references in userdata.  `Lua::scope` *forces* the types to be destructed at the exit of the scope.

**Comment by kyren** [comment]
Changed the documentation in the guided tour, hopefully this is clearer.

Also for future reference in case somebody looks at this issue, what I wrote about `UserData` types requiring `'static` is no longer true, `Scope` can now lift both `Send` and `'static` requirements.
