### ISSUE TITLE
Functions are !Send

### ISSUE THREAD

**Issue by c410-f3r** [kyren/rlua#83]
`Function` is basically a wrapper of `Lua` and since `Lua` itself is `Send`, is it possible to implement `Send` for `Function`?

**Comment by jonas-schievink** [comment]
`Function` is a reference to a Lua function owned by a `Lua` state, not a wrapper around the state itself. If you send a `Function` to another thread, 2 threads could access the `Lua` state simultaneously, which is unsafe (and why `Lua` is `Send`, but not `Sync`).

**Comment by jonas-schievink** [comment]
Lua just doesn't support this (mostly by design). Lua states aren't thread safe no matter what you do, and even if we'd find a way to keep the `Function` alive and drop the reference correctly you still couldn't perform any interesting operations on the function as the interpreter isn't thread-safe either.

However, it is likely that there is a different solution to your problem, but the only way to share Lua data/functions between threads is to create one Lua state per thread. There's lots of message passing libs for Lua, for example.

**Comment by c410-f3r** [comment]
I learned much with your answer, thanks for helping me =)
