### ISSUE TITLE
Implement FromLua / ToLua for i128 and u128

### ISSUE THREAD

**Issue by AregevDev** [kyren/rlua#90]
I really like the library bindings, but I wish to work with Rust's big integers with Lua, unfortunately I cannot do it at the moment

**Comment by kyren** [comment]
I can simply add conversions with the rest of them in https://github.com/kyren/rlua/blob/master/src/conversion.rs#L222 but this actually brings up a good point.

Right now, those are scalar `as` casts, so they're infallible even if the given integer is out of range, and I think that's probably the wrong behavior?  I probably should be using num_traits::cast there and failing to convert unless the integer fits into Lua's internal integer type.

I mention this because Lua integers are always i64s, so the i128 / u128 casts are kind of especially questionable.

What do you think, would you be okay with those conversions if there was an additional error on out of range?

**Comment by AregevDev** [comment]
Hi, sorry for the delay, I think it will be the same situation as converting i128 to i64 in Rust, what's so different 
`let x = 121232343454234346321234u128;
println!("{}", x as u64);`
That for example gives a warning about overflowing integers and completely corrupts the value...
Maybe you should act like that as well

**Comment by kyren** [comment]
I can't somehow cause a compiler warning, and Rust will only give you a warning when it can statically know the value will overflow.

I think the right answer is probably to error like other conversion problems, and if I make that change this patch I'll include i128 and u128 conversion.

**Comment by kyren** [comment]
Done (with the addition of erroring on out of range) and should be in the next release.

**Comment by kyren** [comment]
Okay, there's a new set of conversion behavior which I'm not 100% happy with but I can't think of anything really better.

The big change is that `lua.eval::<i32>("1.5", None)` or similar will yield `Ok(1)` not `Err`, which is consistent with how `num_traits::cast` works.

It's kind of a footgun, but *technically* converting between f64 and f32 could be just as much of a footgun and that was already possible, and it matches how inside Lua itself numbers are very loosely typed.  Also `num_traits::cast` seems to be the "standard" way to do fallible numeric casts in Rust?

Anyway, along with all this you can now cast i128 and u128 and very large integers will just convert to `lua_Number` inside Lua, which is what you'd expect.

**Comment by AregevDev** [comment]
Sounds convenient, is it out yet?
